# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fzzkill/Project/YoLang

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fzzkill/Project/YoLang

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fzzkill/Project/YoLang/CMakeFiles /home/fzzkill/Project/YoLang//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fzzkill/Project/YoLang/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named yolang

# Build rule for target.
yolang: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yolang
.PHONY : yolang

# fast build rule for target.
yolang/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/build
.PHONY : yolang/fast

bytecode/generator.o: bytecode/generator.cpp.o
.PHONY : bytecode/generator.o

# target to build an object file
bytecode/generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/bytecode/generator.cpp.o
.PHONY : bytecode/generator.cpp.o

bytecode/generator.i: bytecode/generator.cpp.i
.PHONY : bytecode/generator.i

# target to preprocess a source file
bytecode/generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/bytecode/generator.cpp.i
.PHONY : bytecode/generator.cpp.i

bytecode/generator.s: bytecode/generator.cpp.s
.PHONY : bytecode/generator.s

# target to generate assembly for a file
bytecode/generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/bytecode/generator.cpp.s
.PHONY : bytecode/generator.cpp.s

console/yoshell.o: console/yoshell.cpp.o
.PHONY : console/yoshell.o

# target to build an object file
console/yoshell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/console/yoshell.cpp.o
.PHONY : console/yoshell.cpp.o

console/yoshell.i: console/yoshell.cpp.i
.PHONY : console/yoshell.i

# target to preprocess a source file
console/yoshell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/console/yoshell.cpp.i
.PHONY : console/yoshell.cpp.i

console/yoshell.s: console/yoshell.cpp.s
.PHONY : console/yoshell.s

# target to generate assembly for a file
console/yoshell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/console/yoshell.cpp.s
.PHONY : console/yoshell.cpp.s

exception/yoexc.o: exception/yoexc.cpp.o
.PHONY : exception/yoexc.o

# target to build an object file
exception/yoexc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/exception/yoexc.cpp.o
.PHONY : exception/yoexc.cpp.o

exception/yoexc.i: exception/yoexc.cpp.i
.PHONY : exception/yoexc.i

# target to preprocess a source file
exception/yoexc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/exception/yoexc.cpp.i
.PHONY : exception/yoexc.cpp.i

exception/yoexc.s: exception/yoexc.cpp.s
.PHONY : exception/yoexc.s

# target to generate assembly for a file
exception/yoexc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/exception/yoexc.cpp.s
.PHONY : exception/yoexc.cpp.s

lexer/lexer.o: lexer/lexer.cpp.o
.PHONY : lexer/lexer.o

# target to build an object file
lexer/lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/lexer/lexer.cpp.o
.PHONY : lexer/lexer.cpp.o

lexer/lexer.i: lexer/lexer.cpp.i
.PHONY : lexer/lexer.i

# target to preprocess a source file
lexer/lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/lexer/lexer.cpp.i
.PHONY : lexer/lexer.cpp.i

lexer/lexer.s: lexer/lexer.cpp.s
.PHONY : lexer/lexer.s

# target to generate assembly for a file
lexer/lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/lexer/lexer.cpp.s
.PHONY : lexer/lexer.cpp.s

parser/AST.o: parser/AST.cpp.o
.PHONY : parser/AST.o

# target to build an object file
parser/AST.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/parser/AST.cpp.o
.PHONY : parser/AST.cpp.o

parser/AST.i: parser/AST.cpp.i
.PHONY : parser/AST.i

# target to preprocess a source file
parser/AST.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/parser/AST.cpp.i
.PHONY : parser/AST.cpp.i

parser/AST.s: parser/AST.cpp.s
.PHONY : parser/AST.s

# target to generate assembly for a file
parser/AST.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/parser/AST.cpp.s
.PHONY : parser/AST.cpp.s

parser/parser.o: parser/parser.cpp.o
.PHONY : parser/parser.o

# target to build an object file
parser/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/parser/parser.cpp.o
.PHONY : parser/parser.cpp.o

parser/parser.i: parser/parser.cpp.i
.PHONY : parser/parser.i

# target to preprocess a source file
parser/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/parser/parser.cpp.i
.PHONY : parser/parser.cpp.i

parser/parser.s: parser/parser.cpp.s
.PHONY : parser/parser.s

# target to generate assembly for a file
parser/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/parser/parser.cpp.s
.PHONY : parser/parser.cpp.s

yolang.o: yolang.cpp.o
.PHONY : yolang.o

# target to build an object file
yolang.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yolang.cpp.o
.PHONY : yolang.cpp.o

yolang.i: yolang.cpp.i
.PHONY : yolang.i

# target to preprocess a source file
yolang.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yolang.cpp.i
.PHONY : yolang.cpp.i

yolang.s: yolang.cpp.s
.PHONY : yolang.s

# target to generate assembly for a file
yolang.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yolang.cpp.s
.PHONY : yolang.cpp.s

yvm/core/storage/scope.o: yvm/core/storage/scope.cpp.o
.PHONY : yvm/core/storage/scope.o

# target to build an object file
yvm/core/storage/scope.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/storage/scope.cpp.o
.PHONY : yvm/core/storage/scope.cpp.o

yvm/core/storage/scope.i: yvm/core/storage/scope.cpp.i
.PHONY : yvm/core/storage/scope.i

# target to preprocess a source file
yvm/core/storage/scope.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/storage/scope.cpp.i
.PHONY : yvm/core/storage/scope.cpp.i

yvm/core/storage/scope.s: yvm/core/storage/scope.cpp.s
.PHONY : yvm/core/storage/scope.s

# target to generate assembly for a file
yvm/core/storage/scope.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/storage/scope.cpp.s
.PHONY : yvm/core/storage/scope.cpp.s

yvm/core/storage/space.o: yvm/core/storage/space.cpp.o
.PHONY : yvm/core/storage/space.o

# target to build an object file
yvm/core/storage/space.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/storage/space.cpp.o
.PHONY : yvm/core/storage/space.cpp.o

yvm/core/storage/space.i: yvm/core/storage/space.cpp.i
.PHONY : yvm/core/storage/space.i

# target to preprocess a source file
yvm/core/storage/space.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/storage/space.cpp.i
.PHONY : yvm/core/storage/space.cpp.i

yvm/core/storage/space.s: yvm/core/storage/space.cpp.s
.PHONY : yvm/core/storage/space.s

# target to generate assembly for a file
yvm/core/storage/space.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/storage/space.cpp.s
.PHONY : yvm/core/storage/space.cpp.s

yvm/core/storage/value.o: yvm/core/storage/value.cpp.o
.PHONY : yvm/core/storage/value.o

# target to build an object file
yvm/core/storage/value.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/storage/value.cpp.o
.PHONY : yvm/core/storage/value.cpp.o

yvm/core/storage/value.i: yvm/core/storage/value.cpp.i
.PHONY : yvm/core/storage/value.i

# target to preprocess a source file
yvm/core/storage/value.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/storage/value.cpp.i
.PHONY : yvm/core/storage/value.cpp.i

yvm/core/storage/value.s: yvm/core/storage/value.cpp.s
.PHONY : yvm/core/storage/value.s

# target to generate assembly for a file
yvm/core/storage/value.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/storage/value.cpp.s
.PHONY : yvm/core/storage/value.cpp.s

yvm/core/type/YBoolean.o: yvm/core/type/YBoolean.cpp.o
.PHONY : yvm/core/type/YBoolean.o

# target to build an object file
yvm/core/type/YBoolean.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/type/YBoolean.cpp.o
.PHONY : yvm/core/type/YBoolean.cpp.o

yvm/core/type/YBoolean.i: yvm/core/type/YBoolean.cpp.i
.PHONY : yvm/core/type/YBoolean.i

# target to preprocess a source file
yvm/core/type/YBoolean.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/type/YBoolean.cpp.i
.PHONY : yvm/core/type/YBoolean.cpp.i

yvm/core/type/YBoolean.s: yvm/core/type/YBoolean.cpp.s
.PHONY : yvm/core/type/YBoolean.s

# target to generate assembly for a file
yvm/core/type/YBoolean.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/type/YBoolean.cpp.s
.PHONY : yvm/core/type/YBoolean.cpp.s

yvm/core/type/YDecimal.o: yvm/core/type/YDecimal.cpp.o
.PHONY : yvm/core/type/YDecimal.o

# target to build an object file
yvm/core/type/YDecimal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/type/YDecimal.cpp.o
.PHONY : yvm/core/type/YDecimal.cpp.o

yvm/core/type/YDecimal.i: yvm/core/type/YDecimal.cpp.i
.PHONY : yvm/core/type/YDecimal.i

# target to preprocess a source file
yvm/core/type/YDecimal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/type/YDecimal.cpp.i
.PHONY : yvm/core/type/YDecimal.cpp.i

yvm/core/type/YDecimal.s: yvm/core/type/YDecimal.cpp.s
.PHONY : yvm/core/type/YDecimal.s

# target to generate assembly for a file
yvm/core/type/YDecimal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/type/YDecimal.cpp.s
.PHONY : yvm/core/type/YDecimal.cpp.s

yvm/core/type/YInteger.o: yvm/core/type/YInteger.cpp.o
.PHONY : yvm/core/type/YInteger.o

# target to build an object file
yvm/core/type/YInteger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/type/YInteger.cpp.o
.PHONY : yvm/core/type/YInteger.cpp.o

yvm/core/type/YInteger.i: yvm/core/type/YInteger.cpp.i
.PHONY : yvm/core/type/YInteger.i

# target to preprocess a source file
yvm/core/type/YInteger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/type/YInteger.cpp.i
.PHONY : yvm/core/type/YInteger.cpp.i

yvm/core/type/YInteger.s: yvm/core/type/YInteger.cpp.s
.PHONY : yvm/core/type/YInteger.s

# target to generate assembly for a file
yvm/core/type/YInteger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/type/YInteger.cpp.s
.PHONY : yvm/core/type/YInteger.cpp.s

yvm/core/type/YNull.o: yvm/core/type/YNull.cpp.o
.PHONY : yvm/core/type/YNull.o

# target to build an object file
yvm/core/type/YNull.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/type/YNull.cpp.o
.PHONY : yvm/core/type/YNull.cpp.o

yvm/core/type/YNull.i: yvm/core/type/YNull.cpp.i
.PHONY : yvm/core/type/YNull.i

# target to preprocess a source file
yvm/core/type/YNull.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/type/YNull.cpp.i
.PHONY : yvm/core/type/YNull.cpp.i

yvm/core/type/YNull.s: yvm/core/type/YNull.cpp.s
.PHONY : yvm/core/type/YNull.s

# target to generate assembly for a file
yvm/core/type/YNull.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/type/YNull.cpp.s
.PHONY : yvm/core/type/YNull.cpp.s

yvm/core/type/YString.o: yvm/core/type/YString.cpp.o
.PHONY : yvm/core/type/YString.o

# target to build an object file
yvm/core/type/YString.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/type/YString.cpp.o
.PHONY : yvm/core/type/YString.cpp.o

yvm/core/type/YString.i: yvm/core/type/YString.cpp.i
.PHONY : yvm/core/type/YString.i

# target to preprocess a source file
yvm/core/type/YString.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/type/YString.cpp.i
.PHONY : yvm/core/type/YString.cpp.i

yvm/core/type/YString.s: yvm/core/type/YString.cpp.s
.PHONY : yvm/core/type/YString.s

# target to generate assembly for a file
yvm/core/type/YString.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/type/YString.cpp.s
.PHONY : yvm/core/type/YString.cpp.s

yvm/core/type/Ytype.o: yvm/core/type/Ytype.cpp.o
.PHONY : yvm/core/type/Ytype.o

# target to build an object file
yvm/core/type/Ytype.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/type/Ytype.cpp.o
.PHONY : yvm/core/type/Ytype.cpp.o

yvm/core/type/Ytype.i: yvm/core/type/Ytype.cpp.i
.PHONY : yvm/core/type/Ytype.i

# target to preprocess a source file
yvm/core/type/Ytype.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/type/Ytype.cpp.i
.PHONY : yvm/core/type/Ytype.cpp.i

yvm/core/type/Ytype.s: yvm/core/type/Ytype.cpp.s
.PHONY : yvm/core/type/Ytype.s

# target to generate assembly for a file
yvm/core/type/Ytype.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/type/Ytype.cpp.s
.PHONY : yvm/core/type/Ytype.cpp.s

yvm/core/yvm.o: yvm/core/yvm.cpp.o
.PHONY : yvm/core/yvm.o

# target to build an object file
yvm/core/yvm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/yvm.cpp.o
.PHONY : yvm/core/yvm.cpp.o

yvm/core/yvm.i: yvm/core/yvm.cpp.i
.PHONY : yvm/core/yvm.i

# target to preprocess a source file
yvm/core/yvm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/yvm.cpp.i
.PHONY : yvm/core/yvm.cpp.i

yvm/core/yvm.s: yvm/core/yvm.cpp.s
.PHONY : yvm/core/yvm.s

# target to generate assembly for a file
yvm/core/yvm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolang.dir/build.make CMakeFiles/yolang.dir/yvm/core/yvm.cpp.s
.PHONY : yvm/core/yvm.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... yolang"
	@echo "... bytecode/generator.o"
	@echo "... bytecode/generator.i"
	@echo "... bytecode/generator.s"
	@echo "... console/yoshell.o"
	@echo "... console/yoshell.i"
	@echo "... console/yoshell.s"
	@echo "... exception/yoexc.o"
	@echo "... exception/yoexc.i"
	@echo "... exception/yoexc.s"
	@echo "... lexer/lexer.o"
	@echo "... lexer/lexer.i"
	@echo "... lexer/lexer.s"
	@echo "... parser/AST.o"
	@echo "... parser/AST.i"
	@echo "... parser/AST.s"
	@echo "... parser/parser.o"
	@echo "... parser/parser.i"
	@echo "... parser/parser.s"
	@echo "... yolang.o"
	@echo "... yolang.i"
	@echo "... yolang.s"
	@echo "... yvm/core/storage/scope.o"
	@echo "... yvm/core/storage/scope.i"
	@echo "... yvm/core/storage/scope.s"
	@echo "... yvm/core/storage/space.o"
	@echo "... yvm/core/storage/space.i"
	@echo "... yvm/core/storage/space.s"
	@echo "... yvm/core/storage/value.o"
	@echo "... yvm/core/storage/value.i"
	@echo "... yvm/core/storage/value.s"
	@echo "... yvm/core/type/YBoolean.o"
	@echo "... yvm/core/type/YBoolean.i"
	@echo "... yvm/core/type/YBoolean.s"
	@echo "... yvm/core/type/YDecimal.o"
	@echo "... yvm/core/type/YDecimal.i"
	@echo "... yvm/core/type/YDecimal.s"
	@echo "... yvm/core/type/YInteger.o"
	@echo "... yvm/core/type/YInteger.i"
	@echo "... yvm/core/type/YInteger.s"
	@echo "... yvm/core/type/YNull.o"
	@echo "... yvm/core/type/YNull.i"
	@echo "... yvm/core/type/YNull.s"
	@echo "... yvm/core/type/YString.o"
	@echo "... yvm/core/type/YString.i"
	@echo "... yvm/core/type/YString.s"
	@echo "... yvm/core/type/Ytype.o"
	@echo "... yvm/core/type/Ytype.i"
	@echo "... yvm/core/type/Ytype.s"
	@echo "... yvm/core/yvm.o"
	@echo "... yvm/core/yvm.i"
	@echo "... yvm/core/yvm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

